export const FETCH_MESSAGES_REQUEST = 'FETCH_MESSAGES_REQUEST'
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS'
export const FETCH_MESSAGES_FAILURE = 'FETCH_MESSAGES_FAILURE'

export const FETCH_GOOGLE_AUTH_REQUEST = 'FETCH_GOOGLE_AUTH_REQUEST'
export const FETCH_GOOGLE_AUTH_SUCCESS = 'FETCH_GOOGLE_AUTH_SUCCESS'

export const FETCH_SIGNUP_FAILURE = 'FETCH_SIGNUP_FAILURE'
export const FETCH_SIGNUP_REQUEST = 'FETCH_SIGNUP_REQUEST'
export const FETCH_SIGNUP_SUCCESS = 'FETCH_SIGNUP_SUCCESS'

export const FETCH_UPDATE_PASSWORD_FAILURE = 'FETCH_UPDATE_PASSWORD_FAILURE'
export const FETCH_UPDATE_PASSWORD_REQUEST = 'FETCH_UPDATE_PASSWORD_REQUEST'
export const FETCH_UPDATE_PASSWORD_SUCCESS = 'FETCH_UPDATE_PASSWORD_SUCCESS'

export const FETCH_RECOVER_PASSWORD_FAILURE = 'FETCH_RECOVER_PASSWORD_FAILURE'
export const FETCH_RECOVER_PASSWORD_REQUEST = 'FETCH_RECOVER_PASSWORD_REQUEST'
export const FETCH_RECOVER_PASSWORD_SUCCESS = 'FETCH_RECOVER_PASSWORD_SUCCESS'

export const FETCH_CLEAR_MESSAGES = 'FETCH_CLEAR_MESSAGES'
export const FETCH_CLEAR_MESSAGES_SUCCESS = 'FETCH_CLEAR_MESSAGES_SUCCESS'

export const FETCH_LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST'
export const FETCH_LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS'
